### ISSUE TITLE
get some errors

### ISSUE THREAD

**Issue by danieldocki** [idoberko2/dokku-deploy-github-action#1]
```
error: failed to push some refs to 'dokku@server:project'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

but locally resolved with `git push dokku master`

**Comment by idoberko2** [comment]
Thanks for your input.

My first intention was to deploy the latest commit being merged, which is done by: 
https://github.com/idoberko2/dokku-deploy-github-action/blob/858004fdfd519b54a538375be2c2031994a722c5/entrypoint.sh#L10

Can you confirm you first pushed one or more advanced commit(s) to the `master` branch on the dokku instance?
In that case, I'm not sure whether that's a bug or a feature.

**Comment by danieldocki** [comment]
@idoberko2 

I using git flow....

![Screen Shot 2020-01-08 at 15 43 06](https://user-images.githubusercontent.com/10542/72006081-a9171200-322d-11ea-8f53-0b4b5c3616a9.png)


But I don't know the relation about this error, cuz manual is working `git push dokku master`

**Comment by ohld** [comment]
I have the same problem. Manual “got push docker master” works fine but Action produce the same error. 

Maybe we’ve configured git on dokku’s machine wrongly.

**Comment by idoberko2** [comment]
Hey @ohld, I'm trying to investigate right now, hopefully I would have additional information soon

**Comment by idoberko2** [comment]
@danieldocki @ohld, please take a look at #2 and tell me what you think.

**Comment by ohld** [comment]
@idoberko2 I am not familiar with git, to be honest. If that can solve the current issue - this is great.

**Comment by idoberko2** [comment]
@danieldocki @ohld you may now add `git-push-flags: '--force'` to the action and it would allow you to push from both your local environment and the GH action. Let me know how it goes!

**Comment by danieldocki** [comment]
@idoberko2  now workings, but I get this error

`
! [remote rejected] b624dd9f0569234f943684f2176c9b9a3c6ab852 -> master (shallow update not allowed)
`

**Comment by ohld** [comment]
@idoberko2 Just tested it also and got the same error as above.

Moreover, since the remote machine has been trying to build the prject, I can't deploy it manually with classic `git push dokku master`. And I have to wait for GitHub actions to fail to deploy the project manually.

**Comment by idoberko2** [comment]
Is the repo public? If so, can you share a link?
If not, can you attach your `.yml` action here?

**Comment by ohld** [comment]
The repo is private. This is `.yml`:
``` yml
name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - id: deploy
      name: Deploy to dokku
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: '<MYHOST>'
          app-name: '<MYAPPNAME>'
          git-push-flags: '--force'```

**Comment by danieldocki** [comment]
```yml
name: Deploy dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: '<HOST>'
            app-name: '<APP>'
            git-push-flags: '--force'
```

**Comment by ohld** [comment]
Any update on this?

**Comment by idoberko2** [comment]
Can you try to change the checkout action like this and let me know how it goes:
```
steps:
  - uses: actions/checkout@v2
    with:
        fetch-depth: 0
```
