### ISSUE TITLE
Add support for DOKKU_SCALE

### ISSUE THREAD

**Issue by john-doherty** [idoberko2/dokku-deploy-github-action#5]
It would be great if you could add support for creating/overwriting the `DOKKU_SCALE` file

```yml
    - uses: idoberko2/dokku-deploy-github-action@v1
      with:
          ssh-private-key: ${{ secrets.DOKKU_SSH }}
          dokku-host: 'myapi.com'
          app-name: 'api'
          dokku-scale: 'web=2'
```

Could execute

```bash
echo web=2 > DOKKU_SCALE
```
